In [3]:
import random
import numpy as np
import torch
from models.rfv_autoencoder import RFVEncoder, RFVDecoder, RFVAutoEncoder
from torch import nn

SEED = 54

np.random.seed(SEED)
random.seed(SEED)
torch.manual_seed(SEED)

# data generation
X = np.random.randint(0, 2, size=(1, 38))

rfv_encoder = RFVEncoder(input_dim=38,hidden_dim=[64,32,16],output_dim=8)
rfv_decoder = RFVDecoder(input_dim=8,hidden_dim=[16,32,64],output_dim=38)
rfv_auto_encoder = RFVAutoEncoder(encoder=rfv_encoder,decoder=rfv_decoder).cuda()
rfv_auto_encoder.load_state_dict(torch.load("best_model/rfv_autoencoder.pth", weights_only=True))
rfv_auto_encoder.eval()
with torch.no_grad():
    y_pred = torch.sigmoid(rfv_auto_encoder(torch.FloatTensor(X).cuda()))
    y_pred = (y_pred > 0.5).float()
    print(y_pred)
    print(torch.FloatTensor(X).cuda())

tensor([[1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1.,
         0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1.,
         0., 1.]], device='cuda:0')
tensor([[1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
         0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0.,
         0., 1.]], device='cuda:0')


In [6]:
with torch.no_grad():
    vector = rfv_auto_encoder.encoder(torch.FloatTensor(X).cuda())
    print(torch.sigmoid(vector))
    print(vector.shape)

tensor([[0.2513, 0.9935, 0.9070, 0.2314, 0.2895, 0.0037, 0.2936, 0.0860]],
       device='cuda:0')
torch.Size([1, 8])
